export const GET_USER_NAME = "USER/GET_USER_NAME";
export const GET_EMAIL = "USER/GET_EMAIL";
export const GET_USER_PHOTO = "USER/GET_USER_PHOTO";
export const GET_EMAIL_VERIFIED = "USER/GET_EMAIL_VERIFIED";
export const CLEAR_USER = "USER/CLEAR_USER";